# Generated by Django 4.1.3 on 2022-11-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='total_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servico',
            name='total_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servico',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
